name: Continuous integration

on:
    pull_request:
        branches:
            master

permissions:
    contents: read
    pull-requests: read

jobs:
    update-environments:
        name: "Update environments"
        uses: ./.github/workflows/devcontainer.yml
